// Generated by CoffeeScript 1.6.3
/*
#
# chainof.coffee
# Author:nikezono
#
*/

module.exports = function() {
  var functions;
  functions = [];
  return {
    use: function(func) {
      throw new Error("Incompatible Type is used for chainof");
    },
    length: function() {
      return functions.length;
    },
    clear: function() {
      return functions = [];
    }
  };
};
